#ifndef GENZ_CLASS_DOT_H
#define GENZ_CLASS_DOT_H

#include "genz_baseline.h"

/**
  * Gen-Z 1.0 Appendix C, Component Class Encodings.
  * NB == Non-Bootable
  * NC == Non-Coherent
  */

enum genz_component_class_encodings {
	GENZ_CCE_RESERVED_SHALL_NOT_BE_USED = 0x0,
	GENZ_CCE_MEMORY_P2P_CORE,
	GENZ_CCE_MEMORY_EXPLICIT_OPCLASS,
	GENZ_CCE_INTEGRATED_SWITCH,
	GENZ_CCE_ENC_EXP_SWITCH,
	GENZ_CCE_FABRIC_SWITCH,
	GENZ_CCE_PROCESSOR,
	GENZ_CCE_PROCESSOR_NB,
	GENZ_CCE_ACCELERATOR_NB_NC = 0x8,
	GENZ_CCE_ACCELERATOR_NB,
	GENZ_CCE_ACCELERATOR_NC,
	GENZ_CCE_ACCELERATOR,
	GENZ_CCE_IO_NB_NC,
	GENZ_CCE_IO_NB,
	GENZ_CCE_IO_NC,
	GENZ_CCE_IO,
	GENZ_CCE_BLOCK_STORAGE = 0x10,
	GENZ_CCE_BLOCK_STORAGE_NB,
	GENZ_CCE_TRANSPARENT_ROUTER,
	GENZ_CCE_MULTI_CLASS,
	GENZ_CCE_DISCRETE_BRIDGE,
	GENZ_CCE_INTEGRATED_BRIDGE = 0x15,
	GENZ_CCE_TOO_BIG,
};

#endif
